export const SPLIT_TYPE_KEY = {
  FULL_BODY_WORKOUT: 'FULL_BODY_WORKOUT',
  SPLIT_3_DAY_WORKOUT: 'SPLIT_3_DAY_WORKOUT',
  SPLIT_5_DAY_WORKOUT: 'SPLIT_5_DAY_WORKOUT',
};

export const SPLIT_TYPE = {
  [SPLIT_TYPE_KEY.FULL_BODY_WORKOUT]: '무분할',
  [SPLIT_TYPE_KEY.SPLIT_3_DAY_WORKOUT]: '3분할',
  [SPLIT_TYPE_KEY.SPLIT_5_DAY_WORKOUT]: '5분할',
};

export const EXERCISE_PART = {
  SHOULDER: '어깨',
  ARM: '팔', // 이두 + 삼두
  CHEST: '가슴',
  BACK: '등',
  LOWER: '하체',
  TRICEPS: '삼두',
  BICEPS: '이두',
};

export const SPLIT_3DAY_EXERCISE_PART = {
  LOWER_AND_SHOULDER: '하체/어깨',
  CHEST_AND_BICEPS: '가슴/이두',
  BACK_AND_TRICEPS: '등/삼두',
};

export const EXERCISE_PART_BY_SPLIT_TYPE = {
  [SPLIT_TYPE_KEY.FULL_BODY_WORKOUT]: {},
  [SPLIT_TYPE_KEY.SPLIT_3_DAY_WORKOUT]: SPLIT_3DAY_EXERCISE_PART,
  [SPLIT_TYPE_KEY.SPLIT_5_DAY_WORKOUT]: EXERCISE_PART,
};
